# Generated by Django 4.1.3 on 2022-11-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todolist_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
